### ISSUE TITLE
Question about your calculation of adequacy prenatal care utilization (APNCU)

### ISSUE THREAD

**Issue by Yizhi-Liang** [uva-bi-sdad/sdc.all#2]
Hi,

I am a master student at Harvard T.H. Chan School of Public Health. I am working on the computation of APNCU using US natality data. I translated [the SAS code](https://www.mchlibrary.org/databases/HSNRCPDFs/APNCU994_20SAS.pdf) written by Dr. Kotelchuck into R, but the proportion is slightly different from what they reported for [the Healthy People 2030 project](https://health.gov/healthypeople/objectives-and-data/browse-objectives/pregnancy-and-childbirth/increase-proportion-pregnant-women-who-receive-early-and-adequate-prenatal-care-mich-08/data?tab=data-table#data-table).

I noticed that the file in this repository [data/sdc.health/Population Health/Reproductive Health/Prenatal Care Adequacy/code/distribution/prepare.Rmd] recorded a way to compute APNCU. May I ask why you compute it in this way? Have you compared the results here with the Healthy 2030 project or other literature? Have you published papers or reports using this method that I can cite or refer to?

I very much appreciate your help.

Yizhi
All the best

**Comment by wanghalan** [comment]
Cesar ([cpm9w@virginia.edu](mailto:cpm9w@virginia.edu)) reached out to Yizhi and resolved the issue offline
